### ISSUE TITLE
Black page?

### ISSUE THREAD

**Issue by grvy** [robgeerts/dashticz_v2#175]
With the following config (pasted/put together with diffrrent examples from the wiki) i either get nothing or I get a black page.. I get no nu.nl feed, I get no weather.. if I use the auto variable (use favorites) I do get something.. however trying to piece together (the wiki is really unclear..) a config.js will lead to a black page.

There also seems to be different types of config.js some with different variables.

config:
```
var config = {}
config['domoticz_ip'] = 'http://192.168.178.36:8080';
config['app_title'] = 'Dashticz';
config['domoticz_refresh'] = '5';
config['dashticz_refresh'] = '60';
config['default_news_url'] = 'http://www.nu.nl/rss/algemeen';
config['news_scroll_after'] = '7';
config['standby_after'] = 0;
config['auto_swipe_back_to'] = 1;
config['auto_swipe_back_after'] = '10';
config['auto_slide_pages'] = 0;
config['slide_effect'] = 'slide';
config['standard_graph'] = 'hours';
config['language'] = 'nl_NL';
config['timeformat'] = 'DD-MM-YY HH:mm';
config['calendarformat'] = 'dd DD.MM HH:mm';
config['calendarlanguage'] = 'en_US';
config['calendarurl'] = 0;
config['boss_stationclock'] = 'RedBoss';
config['gm_api'] = 0;
config['gm_zoomlevel'] = 0;
config['gm_latitude'] = 0;
config['gm_longitude'] = 0;
config['wu_api'] = 0;
config['wu_city'] = 'Amsterdam';
config['wu_name'] = 0;
config['wu_country'] = 'NL';
config['idx_moonpicture'] = 0;
config['switch_horizon'] = 0;
config['host_nzbget'] = 0;
config['spot_clientid'] = 0;
config['garbage_company'] = 0;
config['garbage_icalurl'] = 0;
config['garbage_zipcode'] = 0;
config['garbage_street'] = 0;
config['garbage_housenumber'] = 0;
config['garbage_maxitems'] = 0;
config['garbage_width'] = 0;
config['selector_instead_of_buttons'] = 0;
config['auto_positioning'] = 0;
config['use_favorites'] = 0;
config['last_update'] = 1;
config['hide_topbar'] = 0;
config['hide_seconds'] = 0;
config['hide_seconds_stationclock'] = 0;
config['use_fahrenheit'] = 0;
config['use_beaufort'] = 0;
config['translate_windspeed'] = 1;
config['static_weathericons'] = 0;
config['hide_mediaplayer'] = 0;
config['garbage_hideicon'] = 0;


var buttons = {}
buttons.radio = {width:12, image: 'img/radio_on.png', title: 'Radio', url: 'http://nederland.fm'}
buttons.nunl = {width:12, icon: 'fa-newspaper-o', title: 'Nu.nl', url: 'http://www.nu.nl'}


var blocks = {}
blocks['news_games'] = {}
blocks['news_games']['feed'] = 'http://www.nu.nl/rss/Games';
blocks['news_thn'] = {}
blocks['news_thn']['feed'] = 'http://thehackernews.com/feeds/posts/default?alt=rss';

var columns = {}
columns[1] = {}
columns[1]['blocks'] = ['clock','sunrise',buttons.buinradar] 
columns[1]['width'] = 2;

columns[2] = {}
columns[2]['blocks'] = ['currentweather_big','weather','news']
columns[2]['width'] = 5; 
 
columns[3] = {}
columns[3]['blocks'] = ['news_games','news_thn',buttons.radio,calendars.private]
columns[3]['width'] = 5;

```

**Comment by robgeerts** [comment]
The config as you are using it is correct.
Although, theres 'calendars.private' but this is not defined.. so remove it...
The same for buttons.buinradar....

The weather isnt working because you need a Wunderground-api key...
`config['wu_api'] = 0;`

News isnt working because these websites wont allow your access.... it does work if you enter it like in the config below..
Try these config:
`
var config = {}
config['domoticz_ip'] = 'http://192.168.178.36:8080';
config['app_title'] = 'Dashticz';
config['domoticz_refresh'] = '5';
config['dashticz_refresh'] = '60';
config['default_news_url'] = 'https://cors-anywhere.herokuapp.com/https://www.nu.nl/rss/algemeen';
config['news_scroll_after'] = '7';
config['standby_after'] = 0;
config['auto_swipe_back_to'] = 1;
config['auto_swipe_back_after'] = '10';
config['auto_slide_pages'] = 0;
config['slide_effect'] = 'slide';
config['standard_graph'] = 'hours';
config['language'] = 'nl_NL';
config['timeformat'] = 'DD-MM-YY HH:mm';
config['calendarformat'] = 'dd DD.MM HH:mm';
config['calendarlanguage'] = 'en_US';
config['calendarurl'] = 0;
config['boss_stationclock'] = 'RedBoss';
config['gm_api'] = 0;
config['gm_zoomlevel'] = 0;
config['gm_latitude'] = 0;
config['gm_longitude'] = 0;
config['wu_api'] = 0;
config['wu_city'] = 'Amsterdam';
config['wu_name'] = 0;
config['wu_country'] = 'NL';
config['idx_moonpicture'] = 0;
config['switch_horizon'] = 0;
config['host_nzbget'] = 0;
config['spot_clientid'] = 0;
config['garbage_company'] = 0;
config['garbage_icalurl'] = 0;
config['garbage_zipcode'] = 0;
config['garbage_street'] = 0;
config['garbage_housenumber'] = 0;
config['garbage_maxitems'] = 0;
config['garbage_width'] = 0;
config['selector_instead_of_buttons'] = 0;
config['auto_positioning'] = 0;
config['use_favorites'] = 0;
config['last_update'] = 1;
config['hide_topbar'] = 0;
config['hide_seconds'] = 0;
config['hide_seconds_stationclock'] = 0;
config['use_fahrenheit'] = 0;
config['use_beaufort'] = 0;
config['translate_windspeed'] = 1;
config['static_weathericons'] = 0;
config['hide_mediaplayer'] = 0;
config['garbage_hideicon'] = 0;


var buttons = {}
buttons.radio = {width:12, image: 'img/radio_on.png', title: 'Radio', url: 'http://nederland.fm'}
buttons.nunl = {width:12, icon: 'fa-newspaper-o', title: 'Nu.nl', url: 'http://www.nu.nl'}


var blocks = {}
blocks['news_games'] = {}
blocks['news_games']['feed'] = 'https://cors-anywhere.herokuapp.com/https://www.nu.nl/rss/Games';
blocks['news_thn'] = {}
blocks['news_thn']['feed'] = 'https://cors-anywhere.herokuapp.com/http://thehackernews.com/feeds/posts/default?alt=rss';

var columns = {}
columns[1] = {}
columns[1]['blocks'] = ['clock','sunrise'] 
columns[1]['width'] = 2;

columns[2] = {}
columns[2]['blocks'] = ['currentweather_big','weather','news']
columns[2]['width'] = 5; 
 
columns[3] = {}
columns[3]['blocks'] = ['news_games','news_thn',buttons.radio]
columns[3]['width'] = 5;
`

**Comment by grvy** [comment]
Hello, 

This is the result of the posted config;

![afbeelding](https://user-images.githubusercontent.com/5603820/32058232-c4b111a2-ba69-11e7-95d5-281505d1f0d6.png)

I am really unsure of what im doing wrong. I used git clone to install dashticz.

**Comment by DewGew** [comment]
Your ipaddress looks strange also to many numbers??
Maybe you are using login to domoticz? Then you need to change the domoticz ip in your config file e.g.
http://username:password@192.168.100:8080
Br DewGew

**Comment by robgeerts** [comment]
Dont know if you sorted this out already but the result from your printscreen is correct.
You didnt specify any switches yet.

Add a switch, with IDX 34 (for example) like:

```
columns[2] = {}
columns[2]['blocks'] = ['currentweather_big','weather','news',34]
columns[2]['width'] = 5; 
```
